development:
  dialect: mysql
  datasource: "root:secret@tcp(mysql:3306)/event?parseTime=true&multiStatements=true"
  dir: migrations
  table: schema_migrations
production:
  dialect: mysql
  datasource: ${DATABASE_URL}
  dir: migrations
  table: schema_migrations
