services:
  api:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: docker/images/api/Dockerfile
    volumes:
      - ./:/usr/src/events
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: event
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mysql_data:
    driver: local
  go_modules:
    driver: local
  go_build_cache:
    driver: local
